### ISSUE TITLE
Cannot read property 'trigger' of null

### ISSUE THREAD

**Issue by GCorbel** [altrim/ember-cli-tooltipster#40]
Hi,

I have a tooltip with a link like this :

```
{{#tool-tipster tagName='span' title=(t 'kohordeAdmin.forms.index.edit') theme="tooltipster-light" animation="grow" side="bottom"}}
  {{#link-to 'kohorde-admin.forms/edit' form class='edit'}}
    <i class="fa fa-pencil fa-lg" aria-hidden="true"></i>
  {{/link-to}} 
{{/tool-tipster}}
```
When I click on the link, I have `Cannot read property 'trigger' of null`. It produce the error [at this line](https://github.com/iamceege/tooltipster/blob/99ed4fb784fa88f11557bdc713f4207cb9365431/src/js/tooltipster.js#L2325). 

I think it do this because the the tooltip is not destroyed before the transition. When I scroll, I have `Cannot read property 'attr' of null` at [this line](https://github.com/iamceege/tooltipster/blob/99ed4fb784fa88f11557bdc713f4207cb9365431/src/js/tooltipster.js#L3274).

**Comment by altrim** [comment]
Hey @GCorbel sorry for the delay. I managed to reproduce your issue, looks like it's fixed just by making sure to close the tooltip before calling destroy. (https://github.com/altrim/ember-cli-tooltipster/commit/eda1cf36afc698a84ac60a5ace8c716b521d4359) 

I published version `0.8.0` so you can try and see if it solves the issue for you.

**Comment by GCorbel** [comment]
Thanks. I will try tonight.

**Comment by GCorbel** [comment]
Sorry but it doesn't seems to work. I still have the same bug.

**Comment by altrim** [comment]
Hey @GCorbel  can you try to create a small repo that reproduces the issue with version `0.8.0`? I will try to debug that one just to be sure.

**Comment by GCorbel** [comment]
Hi,

I did : https://github.com/GCorbel/bug-tooltipster . I just added an alert box on the will transition of the page1 to wait a little bit. You just have to go from page1 to page2 to reproduce the bug.

**Comment by altrim** [comment]
I think you forgot to push the code in that repo? I can see only the init commit there with no routes and additional code.

**Comment by GCorbel** [comment]
Oups. Sorry. I pushed the changes.

**Comment by altrim** [comment]
Hey @GCorbel just to let you know I've created the issue in the tooltipster library as well https://github.com/iamceege/tooltipster/issues/679 . I managed to reproduce it without ember so looks like the issue is not in the addon but in the tooltipster library.

**Comment by GCorbel** [comment]
Sorry, I know this is a lot of work, but I still have the bug. You can see it in the "demo" project.

**Comment by altrim** [comment]
Since the issue is fixed in the tooltipster library, I will close this one after I release the addon with the new tooltipster version in the config.
